DELETE FROM CADENCIA
DBCC CHECKIDENT ([CADENCIA],RESEED,0)
SELECT * FROM CADENCIA

BULK INSERT CADENCIA
FROM 'C:\Users\imuxi\OneDrive\Escritorio\archivos sql\CADENCIA.csv'
WITH
(
	FIELDTERMINATOR = ',',
	ROWTERMINATOR = '\n',
	FIRSTROW = 2 

)

DELETE FROM CARGO
SELECT * FROM CARGO
DBCC CHECKIDENT ([CARGO],RESEED,0)
BULK INSERT CARGO
FROM 'C:\Users\imuxi\OneDrive\Escritorio\archivos sql\CARGO.csv'
WITH
(
	FIELDTERMINATOR = ',',
	ROWTERMINATOR = '\n',
	FIRSTROW = 2 

)

DELETE FROM CUENTA
SELECT * FROM CUENTA
DBCC CHECKIDENT ([CUENTA],RESEED,0)
BULK INSERT CUENTA
FROM 'C:\Users\imuxi\OneDrive\Escritorio\archivos sql\CUENTA.csv'
WITH
(
	FIELDTERMINATOR = ',',
	ROWTERMINATOR = '\n',
	FIRSTROW = 2 

)
DELETE FROM ESTADO_DE_CADENCIA
SELECT * FROM ESTADO_DE_CADENCIA
DBCC CHECKIDENT ([ESTADO_DE_CADENCIA],RESEED,0)
BULK INSERT ESTADO_DE_CADENCIA
FROM 'C:\Users\imuxi\OneDrive\Escritorio\archivos sql\ESTADO.csv'
WITH
(
	FIELDTERMINATOR = ',',
	ROWTERMINATOR = '\n',
	FIRSTROW = 2 

)
DELETE FROM INDUSTRIA
SELECT * FROM INDUSTRIA
DBCC CHECKIDENT ([INDUSTRIA],RESEED,0)
BULK INSERT INDUSTRIA
FROM 'C:\Users\imuxi\OneDrive\Escritorio\archivos sql\INDUSTRIA.csv'
WITH
(
	FIELDTERMINATOR = ',',
	ROWTERMINATOR = '\n',
	FIRSTROW = 2 

)

DELETE FROM LISTA
SELECT * FROM LISTA
DBCC CHECKIDENT ([LISTA],RESEED,0)
BULK INSERT LISTA
FROM 'C:\Users\imuxi\OneDrive\Escritorio\archivos sql\LISTA.csv'
WITH
(
	FIELDTERMINATOR = ',',
	ROWTERMINATOR = '\n',
	FIRSTROW = 2 

)

DELETE FROM PROGRAMA
SELECT * FROM PROGRAMA
DBCC CHECKIDENT ([PROGRAMA],RESEED,0)
BULK INSERT PROGRAMA
FROM 'C:\Users\imuxi\OneDrive\Escritorio\archivos sql\PROGRAMA.csv'
WITH
(
	FIELDTERMINATOR = ',',
	ROWTERMINATOR = '\n',
	FIRSTROW = 2 

)

DELETE FROM TAMANO_DE_EMPRESA
SELECT * FROM TAMANO_DE_EMPRESA
DBCC CHECKIDENT ([TAMANO_DE_EMPRESA],RESEED,0)
BULK INSERT TAMANO_DE_EMPRESA
FROM 'C:\Users\imuxi\OneDrive\Escritorio\archivos sql\TAMANO.csv'
WITH
(
	FIELDTERMINATOR = ',',
	ROWTERMINATOR = '\n',
	FIRSTROW = 2 

)
DELETE FROM TABLA_HECHOS
SELECT * FROM TABLA_HECHOS
DBCC CHECKIDENT ([TABLA_HECHOS],RESEED,0)
BULK INSERT TABLA_HECHOS
FROM 'C:\Users\imuxi\OneDrive\Escritorio\archivos sql\TABLA_HECHOS.csv'
WITH
(
	FIELDTERMINATOR = ',',
	ROWTERMINATOR = '\n',
	FIRSTROW = 2 

)

SELECT * FROM CUENTA
SELECT * FROM ESTADO_DE_CADENCIA
SELECT * FROM TABLA_HECHOS


-- BUSCAR LAS CADENCIAS ACTIVAS DE LA CUENTA ICAMI
	
SELECT 	NOMBRE_CUENTA "CUENTA CLIENTE", ENVIOS,APERTURA,ESTADO_CADENCIA "ESTADO DE LA CADENCIA"
FROM TABLA_HECHOS
INNER JOIN CUENTA
ON TABLA_HECHOS.ID_CUENTA = CUENTA.ID_CUENTA
INNER JOIN ESTADO_DE_CADENCIA
ON TABLA_HECHOS.ID_ESTADO = ESTADO_DE_CADENCIA.ID_ESTADO
WHERE TABLA_HECHOS.ID_CUENTA = 8 AND TABLA_HECHOS.ID_ESTADO = 1



	

