
CREATE TABLE TABLA_ECHOS(
		ID INT IDENTITY(1,1) PRIMARY KEY,
		ID_DATO INT,
		ID_SUBDATO INT,
		ID_REPORTE INT,
		ID_FECHA INT,
		VALOR NVARCHAR(255)
					    );



CREATE TABLE TABLA_DATO(
	ID_DATO INT IDENTITY(1,1) PRIMARY KEY,
	TIPO_DATO NVARCHAR(255)
                       );
CREATE TABLE TABLA_SUBDATO(
		ID_SUBDATO INT IDENTITY(1,1) PRIMARY KEY,
		TIPO_SUBDATO NVARCHAR(255)
						   );
CREATE TABLE TABLA_FECHA(
		ID_FECHA INT IDENTITY(1,1) PRIMARY KEY,
		FECHA DATETIME
						   );
CREATE TABLE TABLA_REPORTE(
		ID_REPORTE INT IDENTITY(1,1) PRIMARY KEY,
		TIPO_REPORTE NVARCHAR(255)
						   );

ALTER TABLE TABLA_ECHOS 
ADD CONSTRAINT FK1_TABLA_ECHOS
FOREIGN KEY (ID_DATO)
REFERENCES TABLA_DATO(ID_DATO)
ALTER TABLE TABLA_ECHOS 
ADD CONSTRAINT FK2_TABLA_ECHOS
FOREIGN KEY (ID_SUBDATO)
REFERENCES TABLA_SUBDATO(ID_SUBDATO)
ALTER TABLE TABLA_ECHOS 
ADD CONSTRAINT FK3_TABLA_ECHOS
FOREIGN KEY (ID_FECHA)
REFERENCES TABLA_FECHA(ID_FECHA)
ALTER TABLE TABLA_ECHOS 
ADD CONSTRAINT FK4_TABLA_ECHOS
FOREIGN KEY (ID_REPORTE)
REFERENCES TABLA_REPORTE(ID_REPORTE)



SELECT VALOR,ID,FECHA
FROM TABLA_ECHOS TE 
JOIN TABLA_DATO TD
ON TD.ID_DATO = TE.ID_DATO
JOIN TABLA_SUBDATO TSD
ON TSD.ID_SUBDATO = TE.ID_SUBDATO
JOIN TABLA_FECHA TF
ON TF.ID_FECHA = TE.ID_FECHA
JOIN TABLA_REPORTE TR
ON TR.ID_REPORTE = TE.ID_REPORTE
WHERE TE.ID_SUBDATO=63 